### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by Hamza-101** [hbonnavaud/RLFramework#1]
In "agents/value_based_agents/dqn.py":

`from ..utils.nn import MLP
`

returns 

> Import "..utils.nn" could not be resolvedPylance[reportMissingImports]

Also checked the repository manually, no "nn.py" file exists.

Where do I get the file from?

**Comment by hbonnavaud** [comment]
Hi,

Thank you for reporting this.
The file is here https://github.com/hbonnavaud/RLFramework/tree/master/agents/utils (pushed in the first commit 5 days ago according to github) in agents/utils/nn.py

Are you sure you do not have the file? If it is the case there should be an issue in the forking / downloading process I guess.
Otherwise if you have it, it might be an issue with the relative import (maybe it is not supported by Pylance? I don't use it)

I wait for your repply.

**Comment by Hamza-101** [comment]
Ah thanks found it.
